name: qgis3
version: 3.4.4
summary: A Free and Open Source Geographic Information System
description: |
  Create, edit, visualise, analyse and publish geospatial information.
  QGIS feels snappy to use and has a pleasing, easy to use graphical user
  interface. It supports a number of raster and vector data formats, with new
  support easily added using the plugin architectur

grade: devel
confinement: strict
architectures: [amd64]

apps:
  qgis3:
    command: desktop-launch qgis
    plugs: [home, network, unity7]
    environment:
      GDAL_DATA: $SNAP/usr/share/gdal/2.2
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/grass74/lib
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins
      R_ENVIRON: $SNAP/usr/lib/R/etc/Renviron
  ipython:
    command: ipython
    plugs: [home, network, unity7]
    environment:
      GDAL_DATA: $SNAP/usr/share/gdal/2.2
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/grass74/lib
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins
      R_ENVIRON: $SNAP/usr/lib/R/etc/Renviron
  R:
    command: R
    plugs: [home, network, unity7]
    environment:
      GDAL_DATA: $SNAP/usr/share/gdal/2.2
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/grass74/lib
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins
      R_ENVIRON: $SNAP/usr/lib/R/etc/Renviron

parts:
  qgis:
    source: https://github.com/qgis/QGIS/archive/final-3_4_4.tar.gz
    plugin: cmake
    after: [python-deps, desktop-qt5]
    configflags:
      - -DWITH_BINDINGS=TRUE
      - -DWITH_PY_COMPILE=FALSE
      - -DBINDINGS_GLOBAL_INSTALL=TRUE
      - -DPYTHON_SITE_PACKAGES_DIR=/usr/lib/python3.6/dist-packages
      - -DENABLE_TESTS=FALSE
    build-packages:
      - bison
      - ca-certificates
      - ccache
      - dh-python
      - doxygen
      - expect
      - flex
      - graphviz
      - grass-dev
      - libexpat1-dev
      - libfcgi-dev
      - libgdal-dev
      - libgeos-dev
      - libgsl-dev
      - libpq-dev
      - libproj-dev
      - libqca-qt5-2-dev
      - libqca-qt5-2-plugins
      - libqt5opengl5-dev
      - libqt5scintilla2-dev
      - libqt5serialport5-dev
      - libqt5sql5-sqlite
      - libqt5svg5-dev
      - libqt5webkit5-dev
      - libqt5xmlpatterns5-dev
      - libqwt-qt5-dev
      - libspatialindex-dev
      - libspatialite-dev
      - libsqlite3-dev
      - libsqlite3-mod-spatialite
      - libyaml-tiny-perl
      - libzip-dev
      - lighttpd
      - locales
      - ninja-build
      - opencl-headers
      - pkg-config
      - poppler-utils
      - pyqt5-dev
      - pyqt5-dev-tools
      - pyqt5.qsci-dev
      - qt5-default
      - qt5keychain-dev
      - qtbase5-dev
      - qtpositioning5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - spawn-fcgi
      - txt2tags
      - xauth
      - xfonts-100dpi
      - xfonts-75dpi
      - xfonts-base
      - xfonts-scalable
      - xvfb
    stage-packages:
      - libatlas3-base
      - libdb5.3
      - libgsl23
      - libqca-qt5-2
      - libqca-qt5-2-plugins
      - libqca2-plugins
      - libqgisgrass7-3.4.3
      - libqt5concurrent5
      - libqt5keychain1
      - libqt5positioning5
      - libqt5positioning5-plugins
      - libqt5quickwidgets5
      - libqt5sql5-sqlite
      - libqt5serialport5
      - libqwt-qt5-6
      - libspatialindex4v5
      - libzip4
      - ocl-icd-libopencl1
    organize:
      usr/lib/x86_64-linux-gnu/qca-qt5/crypto: usr/lib/x86_64-linux-gnu/qt5/plugins/crypto
    stage:
      - -include/
      - -usr/share/doc
    override-prime: |
      snapcraftctl prime
      set -ex
      cd usr/lib
      ln -sf atlas-base/atlas/libblas.so.3 libblas.so.3
      ln -sf lapack/liblapack.so.3 liblapack.so.3

  python-deps:
    plugin: nil
    stage-packages:
      - python-autopep8
      - python3-all-dev
      - python3-dateutil
      - python3-dev
      - python3-future
      - python3-gdal
      - python3-httplib2
      - python3-jinja2
      - python3-markupsafe
      - python3-mock
      - python3-nose2
      - python3-owslib
      # - python3-plotly
      - python3-psycopg2
      - python3-pygments
      - python3-pyproj
      - python3-pyqt5
      - python3-pyqt5.qsci
      - python3-pyqt5.qtsql
      - python3-pyqt5.qtsvg
      - python3-pyqt5.qtwebkit
      - python3-requests
      - python3-scipy
      - python3-sip
      - python3-sip-dev
      - python3-six
      - python3-termcolor
      - python3-tz
      - python3-yaml

  gis-tools:
    plugin: nil
    stage-packages:
      - gdal-bin
      - grass-core
      - python-saga
      - saga

  stats-tools:
    plugin: nil
    stage-packages:
      - r-base
      - r-cran-ggplot2
      - r-cran-msm
      - r-cran-plyr
      - r-cran-rcolorbrewer
      - r-cran-sp

  python-shell:
    plugin: python
    after: [qgis]
    python-version: python3
    python-packages:
      - ipython
      - mistune
      - pip
      - plotly==3.3